spring:
  gateway:
    discovery:
      locator:
        enabled: true
    routes:
      - id: user-service-login
        uri: lb://user-service
        predicates:
          - Path=/api/user/login
      - id: user-service-register
        uri: lb://user-service
        predicates:
          - Path=/api/user/register
      - id: user-service-password-reset
        uri: lb://user-service
        predicates:
          - Path=/api/user/password/reset
      - id: user-service-account-activate
        uri: lb://user-service
        predicates:
          - Path=/api/link/redirect/activate
  user:
    service:
      url: http://localhost:8082

novaflow:
  services:
    user-base: http://localhost:8082
    user: http://localhost:8082/api/user
    collaborator: http://localhost:8082/api/collaborator
    idea: http://localhost:8083/api/idea
    ai: http://localhost:8084/api/ai
    chat: http://localhost:8085/api/chat
