server:
  port: 8084

spring:
  application:
    name: ai-service

  profiles:
    active: dev

  config:
    import: "configserver:http://localhost:7090/"  # Pull config from config server
    label: develop

  cloud:
    config:
      uri: http://localhost:7090  # Location of config server
      fail-fast: true
      retry:
        max-attempts: 10
        initial-interval: 2000
        multiplier: 1.5
        max-interval: 10000

  liquibase:
    drop-first: false

  jpa:
    show-sql: true
