server:
  port: 7090

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@bitbucket.org:novaflow/common-config.git
          clone-on-start: true
          ignore-local-ssh-settings: true
          private-key: ${CONFIG_SERVER_SSH_KEY}
          strict-host-key-checking: false
          searchPaths: '{application}'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
