#!/usr/bin/env sh
set -eu

SCRIPT_PATH=$0
case "$SCRIPT_PATH" in
    */*) SCRIPT_DIR=${SCRIPT_PATH%/*} ;;
    *) SCRIPT_DIR=. ;;
esac
SCRIPT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR" && pwd)

SSM_ENV_PATH=${SSM_ENV_PATH:-/novaflow/production/env}
SSM_ENV_REGION=${SSM_ENV_REGION:-${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}}
OUTPUT_ENV_FILE=${OUTPUT_ENV_FILE:-"$SCRIPT_DIR/../.env"}

usage() {
    cat <<EOF
Usage:
  SSM_ENV_PATH=/novaflow/production/env sh render-env-from-ssm.sh

Reads all direct child parameters below SSM_ENV_PATH and renders them as a
Docker Compose env file. Parameter names must end in uppercase env keys, such
as /novaflow/production/env/DB_HOST.

Environment overrides:
  SSM_ENV_PATH=/novaflow/production/env
  SSM_ENV_REGION=us-east-1
  OUTPUT_ENV_FILE=/path/to/generated.env
EOF
}

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument '$arg'." >&2
            usage >&2
            exit 1
            ;;
    esac
done

case "$SSM_ENV_PATH" in
    /*) ;;
    *)
        echo "SSM_ENV_PATH must start with '/', got '$SSM_ENV_PATH'." >&2
        exit 1
        ;;
esac

SSM_ENV_PATH=${SSM_ENV_PATH%/}

if ! command -v aws >/dev/null 2>&1; then
    echo "AWS CLI is required to render production env from Parameter Store." >&2
    exit 1
fi

if ! command -v python3 >/dev/null 2>&1; then
    echo "python3 is required to render production env from Parameter Store." >&2
    exit 1
fi

tmp_json=$(mktemp)
tmp_env=$(mktemp)

cleanup() {
    rm -f "$tmp_json" "$tmp_env"
}
trap cleanup EXIT HUP INT TERM

echo "Reading production env parameters from $SSM_ENV_PATH in $SSM_ENV_REGION..."
aws ssm get-parameters-by-path \
    --path "$SSM_ENV_PATH" \
    --recursive \
    --with-decryption \
    --region "$SSM_ENV_REGION" \
    --output json > "$tmp_json"

python3 - "$SSM_ENV_PATH" "$tmp_json" "$tmp_env" <<'PY'
import json
import re
import shlex
import sys

path = sys.argv[1].rstrip("/")
json_file = sys.argv[2]
env_file = sys.argv[3]

with open(json_file, "r", encoding="utf-8") as handle:
    data = json.load(handle)

parameters = data.get("Parameters", [])
if not parameters:
    raise SystemExit(f"No parameters found below {path}.")

env_lines = [
    "# Generated from AWS Systems Manager Parameter Store.",
    f"# Source path: {path}",
    "# Do not edit this file by hand.",
]
seen = set()
errors = []

for parameter in sorted(parameters, key=lambda item: item.get("Name", "")):
    name = parameter.get("Name", "")
    prefix = path + "/"

    if not name.startswith(prefix):
        continue

    key = name[len(prefix):]
    value = parameter.get("Value", "")

    if "/" in key:
        errors.append(f"{name}: nested parameter names are not supported")
        continue

    if not re.fullmatch(r"[A-Z][A-Z0-9_]*", key):
        errors.append(f"{name}: parameter name must end in an uppercase env key")
        continue

    if key in seen:
        errors.append(f"{name}: duplicate env key {key}")
        continue

    if "\n" in value or "\r" in value:
        errors.append(f"{name}: multiline values are not supported")
        continue

    seen.add(key)
    env_lines.append(f"{key}={shlex.quote(value)}")

if errors:
    for error in errors:
        print(error, file=sys.stderr)
    raise SystemExit(1)

with open(env_file, "w", encoding="utf-8") as handle:
    handle.write("\n".join(env_lines))
    handle.write("\n")

print(f"Wrote {len(seen)} env values.")
PY

output_dir=$(dirname "$OUTPUT_ENV_FILE")
mkdir -p "$output_dir"
cat "$tmp_env" > "$OUTPUT_ENV_FILE"
chmod 600 "$OUTPUT_ENV_FILE"
echo "Rendered env file: $OUTPUT_ENV_FILE"
