#!/usr/bin/env sh
set -eu

SCRIPT_PATH=$0
case "$SCRIPT_PATH" in
    */*) SCRIPT_DIR=${SCRIPT_PATH%/*} ;;
    *) SCRIPT_DIR=. ;;
esac
SCRIPT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
COMPOSE_FILE=${COMPOSE_FILE:-"$SCRIPT_DIR/docker-compose.production.yml"}
ENV_FILE=${ENV_FILE:-}
SSM_ENV_PATH=${SSM_ENV_PATH:-}
SSM_ENV_REGION=${SSM_ENV_REGION:-${AWS_REGION:-${AWS_DEFAULT_REGION:-us-east-1}}}
SEED_DATABASE=${SEED_DATABASE:-user_service_db}
SEED_USERNAME=${SEED_USERNAME:-admin}
SEED_EMAIL=${SEED_EMAIL:-admin@novaflow.local}
SEED_NAME=${SEED_NAME:-Admin}
SEED_PASSWORD=${SEED_PASSWORD:-}
USE_EXTERNAL_POSTGRES=${USE_EXTERNAL_POSTGRES:-}

usage() {
    cat <<EOF
Usage:
  SEED_PASSWORD='change-me' sh seed-admin-user.sh

Creates or updates one enabled local ADMIN user in the user-service database.
The password is stored as a BCrypt hash generated by PostgreSQL pgcrypto.

Environment overrides:
  COMPOSE_FILE=/path/to/docker-compose.production.yml
  ENV_FILE=/path/to/.env
  SSM_ENV_PATH=/novaflow/production/env
  SSM_ENV_REGION=us-east-1
  SEED_DATABASE=user_service_db
  SEED_USERNAME=admin
  SEED_EMAIL=admin@novaflow.local
  SEED_NAME=Admin
  SEED_PASSWORD=required
  USE_EXTERNAL_POSTGRES=1
  DB_HOST=novaflow-postgres.xxxxxx.us-east-1.rds.amazonaws.com
  DB_PORT=5432
  DB_USERNAME=novaflow_admin
  DB_PASSWORD=required-for-external-postgres
EOF
}

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument '$arg'." >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [ -z "$SEED_PASSWORD" ]; then
    echo "SEED_PASSWORD is required." >&2
    usage >&2
    exit 2
fi

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "Could not find Docker Compose file: $COMPOSE_FILE" >&2
    exit 1
fi

RENDERED_ENV_FILE=""

cleanup_rendered_env_file() {
    if [ -n "$RENDERED_ENV_FILE" ]; then
        rm -f "$RENDERED_ENV_FILE"
    fi
}
trap cleanup_rendered_env_file EXIT HUP INT TERM

if [ -n "$SSM_ENV_PATH" ]; then
    if [ -n "$ENV_FILE" ]; then
        echo "Both SSM_ENV_PATH and ENV_FILE are set. Refusing to choose between them." >&2
        exit 1
    fi

    RENDERED_ENV_FILE=$(mktemp)
    SSM_ENV_PATH="$SSM_ENV_PATH" \
        SSM_ENV_REGION="$SSM_ENV_REGION" \
        OUTPUT_ENV_FILE="$RENDERED_ENV_FILE" \
        sh "$SCRIPT_DIR/render-env-from-ssm.sh"
    ENV_FILE="$RENDERED_ENV_FILE"
fi

if [ -z "$ENV_FILE" ]; then
    if [ -f "$SCRIPT_DIR/.env" ]; then
        ENV_FILE="$SCRIPT_DIR/.env"
    elif [ -f "$SCRIPT_DIR/../.env" ]; then
        ENV_FILE="$SCRIPT_DIR/../.env"
    elif [ -f "$REPO_ROOT/.env" ]; then
        ENV_FILE="$REPO_ROOT/.env"
    fi
fi

if [ -n "$ENV_FILE" ]; then
    if [ ! -f "$ENV_FILE" ]; then
        echo "Could not find env file: $ENV_FILE" >&2
        exit 1
    fi
    echo "Using env file: $ENV_FILE"
else
    echo "No .env file found. Docker Compose will use the current process environment."
fi

dotenv_get() {
    key=$1

    if [ -z "$ENV_FILE" ] || [ ! -f "$ENV_FILE" ]; then
        return 1
    fi

    value=$(sed -n "s/^[[:space:]]*$key[[:space:]]*=[[:space:]]*//p" "$ENV_FILE" | sed -n '1p')
    [ -n "$value" ] || return 1

    case "$value" in
        \"*\") value=$(printf '%s' "$value" | sed 's/^"//; s/"$//') ;;
        \'*\') value=$(printf '%s' "$value" | sed "s/^'//; s/'$//") ;;
    esac

    printf '%s' "$value"
}

env_or_default() {
    name=$1
    default_value=$2
    eval "value=\${$name:-}"
    if [ -n "$value" ]; then
        printf '%s' "$value"
    elif value=$(dotenv_get "$name" 2>/dev/null); then
        printf '%s' "$value"
    else
        printf '%s' "$default_value"
    fi
}

if [ -z "$USE_EXTERNAL_POSTGRES" ]; then
    USE_EXTERNAL_POSTGRES=$(dotenv_get USE_EXTERNAL_POSTGRES || true)
fi

USE_EXTERNAL_POSTGRES=${USE_EXTERNAL_POSTGRES:-0}
DB_HOST=$(env_or_default DB_HOST postgres)
DB_PORT=$(env_or_default DB_PORT 5432)
POSTGRES_USER_VALUE=$(env_or_default POSTGRES_USER sa)
POSTGRES_PASSWORD_VALUE=$(env_or_default POSTGRES_PASSWORD "")
DB_USERNAME=$(env_or_default DB_USERNAME "$POSTGRES_USER_VALUE")
DB_PASSWORD=$(env_or_default DB_PASSWORD "$POSTGRES_PASSWORD_VALUE")

uses_external_postgres() {
    case "$USE_EXTERNAL_POSTGRES" in
        1|true|TRUE|True|yes|YES|Yes) return 0 ;;
        *) return 1 ;;
    esac
}

if ! uses_external_postgres; then
    if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
        compose() {
            docker compose "$@"
        }
    elif command -v docker-compose >/dev/null 2>&1; then
        compose() {
            docker-compose "$@"
        }
    else
        echo "Could not find 'docker compose' or 'docker-compose'." >&2
        exit 1
    fi
fi

compose_stack() {
    if [ -n "$ENV_FILE" ]; then
        compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
    else
        compose -f "$COMPOSE_FILE" "$@"
    fi
}

run_seed_sql() {
    if uses_external_postgres; then
        if ! command -v psql >/dev/null 2>&1; then
            echo "psql is required when USE_EXTERNAL_POSTGRES=1." >&2
            echo "Install postgresql-client on EC2, then rerun this script." >&2
            exit 1
        fi

        if [ -z "$DB_PASSWORD" ]; then
            echo "DB_PASSWORD is required when USE_EXTERNAL_POSTGRES=1." >&2
            exit 2
        fi

        PGPASSWORD=$DB_PASSWORD psql -v ON_ERROR_STOP=1 \
            -h "$DB_HOST" \
            -p "$DB_PORT" \
            -U "$DB_USERNAME" \
            -d "$SEED_DATABASE" \
            -v seed_username="$SEED_USERNAME" \
            -v seed_email="$SEED_EMAIL" \
            -v seed_name="$SEED_NAME" \
            -v seed_password="$SEED_PASSWORD"
    else
        compose_stack exec -T \
            -e SEED_DATABASE="$SEED_DATABASE" \
            -e SEED_USERNAME="$SEED_USERNAME" \
            -e SEED_EMAIL="$SEED_EMAIL" \
            -e SEED_NAME="$SEED_NAME" \
            -e SEED_PASSWORD="$SEED_PASSWORD" \
            postgres sh -lc '
                psql -v ON_ERROR_STOP=1 \
                    -U "$POSTGRES_USER" \
                    -d "$SEED_DATABASE" \
                    -v seed_username="$SEED_USERNAME" \
                    -v seed_email="$SEED_EMAIL" \
                    -v seed_name="$SEED_NAME" \
                    -v seed_password="$SEED_PASSWORD"
            '
    fi
}

echo "Creating or updating enabled ADMIN user '$SEED_USERNAME' in '$SEED_DATABASE'..."
if uses_external_postgres; then
    echo "Using external PostgreSQL at $DB_HOST:$DB_PORT."
fi

run_seed_sql <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH seed_values AS (
    SELECT
        :'seed_username'::text AS username,
        :'seed_email'::text AS email,
        :'seed_name'::text AS name,
        crypt(:'seed_password', gen_salt('bf', 10)) AS password_hash
),
updated AS (
    UPDATE public.app_user user_record
    SET
        email = seed_values.email,
        name = seed_values.name,
        username = seed_values.username,
        password = seed_values.password_hash,
        role = 'ADMIN',
        auth_provider = 'LOCAL',
        provider_subject = NULL,
        is_account_non_expired = true,
        is_enabled = true,
        is_account_non_locked = true,
        is_credentials_non_expired = true,
        modified_at = CURRENT_TIMESTAMP,
        modified_by = 'seed-admin-user.sh'
    FROM seed_values
    WHERE lower(user_record.username) = lower(seed_values.username)
       OR lower(user_record.email) = lower(seed_values.email)
    RETURNING user_record.id
)
INSERT INTO public.app_user (
    email,
    name,
    username,
    password,
    role,
    auth_provider,
    provider_subject,
    is_account_non_expired,
    is_enabled,
    is_account_non_locked,
    is_credentials_non_expired,
    created_at,
    created_by,
    modified_at,
    modified_by
)
SELECT
    email,
    name,
    username,
    password_hash,
    'ADMIN',
    'LOCAL',
    NULL,
    true,
    true,
    true,
    true,
    CURRENT_TIMESTAMP,
    'seed-admin-user.sh',
    CURRENT_TIMESTAMP,
    'seed-admin-user.sh'
FROM seed_values
WHERE NOT EXISTS (SELECT 1 FROM updated);

DELETE FROM public.account_activation_token
WHERE user_id IN (
    SELECT id
    FROM public.app_user
    WHERE lower(username) = lower(:'seed_username')
       OR lower(email) = lower(:'seed_email')
);

DELETE FROM public.password_reset_token
WHERE user_id IN (
    SELECT id
    FROM public.app_user
    WHERE lower(username) = lower(:'seed_username')
       OR lower(email) = lower(:'seed_email')
);

SELECT username, email, role, auth_provider, is_enabled
FROM public.app_user
WHERE lower(username) = lower(:'seed_username')
   OR lower(email) = lower(:'seed_email')
ORDER BY id;
SQL
echo "Seed admin user is ready."
