#!/usr/bin/env sh
set -eu

SCRIPT_PATH=$0
case "$SCRIPT_PATH" in
    */*) SCRIPT_DIR=${SCRIPT_PATH%/*} ;;
    *) SCRIPT_DIR=. ;;
esac
SCRIPT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR" && pwd)
REPO_ROOT=$(CDPATH= cd -- "$SCRIPT_DIR/../.." && pwd)
COMPOSE_FILE=${COMPOSE_FILE:-"$SCRIPT_DIR/docker-compose.production.yml"}
ENV_FILE=${ENV_FILE:-}
SEED_DATABASE=${SEED_DATABASE:-user_service_db}
SEED_USERNAME=${SEED_USERNAME:-admin}
SEED_EMAIL=${SEED_EMAIL:-admin@novaflow.local}
SEED_NAME=${SEED_NAME:-Admin}
SEED_PASSWORD=${SEED_PASSWORD:-}

usage() {
    cat <<EOF
Usage:
  SEED_PASSWORD='change-me' sh seed-admin-user.sh

Creates or updates one enabled local ADMIN user in the user-service database.
The password is stored as a BCrypt hash generated by PostgreSQL pgcrypto.

Environment overrides:
  COMPOSE_FILE=/path/to/docker-compose.production.yml
  ENV_FILE=/path/to/.env
  SEED_DATABASE=user_service_db
  SEED_USERNAME=admin
  SEED_EMAIL=admin@novaflow.local
  SEED_NAME=Admin
  SEED_PASSWORD=required
EOF
}

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            usage
            exit 0
            ;;
        *)
            echo "Unknown argument '$arg'." >&2
            usage >&2
            exit 1
            ;;
    esac
done

if [ -z "$SEED_PASSWORD" ]; then
    echo "SEED_PASSWORD is required." >&2
    usage >&2
    exit 2
fi

if [ ! -f "$COMPOSE_FILE" ]; then
    echo "Could not find Docker Compose file: $COMPOSE_FILE" >&2
    exit 1
fi

if [ -z "$ENV_FILE" ]; then
    if [ -f "$SCRIPT_DIR/.env" ]; then
        ENV_FILE="$SCRIPT_DIR/.env"
    elif [ -f "$SCRIPT_DIR/../.env" ]; then
        ENV_FILE="$SCRIPT_DIR/../.env"
    elif [ -f "$REPO_ROOT/.env" ]; then
        ENV_FILE="$REPO_ROOT/.env"
    fi
fi

if [ -n "$ENV_FILE" ]; then
    if [ ! -f "$ENV_FILE" ]; then
        echo "Could not find env file: $ENV_FILE" >&2
        exit 1
    fi
    echo "Using env file: $ENV_FILE"
else
    echo "No .env file found. Docker Compose will use the current process environment."
fi

if command -v docker >/dev/null 2>&1 && docker compose version >/dev/null 2>&1; then
    compose() {
        docker compose "$@"
    }
elif command -v docker-compose >/dev/null 2>&1; then
    compose() {
        docker-compose "$@"
    }
else
    echo "Could not find 'docker compose' or 'docker-compose'." >&2
    exit 1
fi

compose_stack() {
    if [ -n "$ENV_FILE" ]; then
        compose --env-file "$ENV_FILE" -f "$COMPOSE_FILE" "$@"
    else
        compose -f "$COMPOSE_FILE" "$@"
    fi
}

echo "Creating or updating enabled ADMIN user '$SEED_USERNAME' in '$SEED_DATABASE'..."
compose_stack exec -T \
    -e SEED_DATABASE="$SEED_DATABASE" \
    -e SEED_USERNAME="$SEED_USERNAME" \
    -e SEED_EMAIL="$SEED_EMAIL" \
    -e SEED_NAME="$SEED_NAME" \
    -e SEED_PASSWORD="$SEED_PASSWORD" \
    postgres sh -lc '
        psql -v ON_ERROR_STOP=1 \
            -U "$POSTGRES_USER" \
            -d "$SEED_DATABASE" \
            -v seed_username="$SEED_USERNAME" \
            -v seed_email="$SEED_EMAIL" \
            -v seed_name="$SEED_NAME" \
            -v seed_password="$SEED_PASSWORD"
    ' <<'SQL'
CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH seed_values AS (
    SELECT
        :'seed_username'::text AS username,
        :'seed_email'::text AS email,
        :'seed_name'::text AS name,
        crypt(:'seed_password', gen_salt('bf', 10)) AS password_hash
),
updated AS (
    UPDATE public.app_user user_record
    SET
        email = seed_values.email,
        name = seed_values.name,
        username = seed_values.username,
        password = seed_values.password_hash,
        role = 'ADMIN',
        auth_provider = 'LOCAL',
        provider_subject = NULL,
        is_account_non_expired = true,
        is_enabled = true,
        is_account_non_locked = true,
        is_credentials_non_expired = true,
        modified_at = CURRENT_TIMESTAMP,
        modified_by = 'seed-admin-user.sh'
    FROM seed_values
    WHERE lower(user_record.username) = lower(seed_values.username)
       OR lower(user_record.email) = lower(seed_values.email)
    RETURNING user_record.id
)
INSERT INTO public.app_user (
    email,
    name,
    username,
    password,
    role,
    auth_provider,
    provider_subject,
    is_account_non_expired,
    is_enabled,
    is_account_non_locked,
    is_credentials_non_expired,
    created_at,
    created_by,
    modified_at,
    modified_by
)
SELECT
    email,
    name,
    username,
    password_hash,
    'ADMIN',
    'LOCAL',
    NULL,
    true,
    true,
    true,
    true,
    CURRENT_TIMESTAMP,
    'seed-admin-user.sh',
    CURRENT_TIMESTAMP,
    'seed-admin-user.sh'
FROM seed_values
WHERE NOT EXISTS (SELECT 1 FROM updated);

DELETE FROM public.account_activation_token
WHERE user_id IN (
    SELECT id
    FROM public.app_user
    WHERE lower(username) = lower(:'seed_username')
       OR lower(email) = lower(:'seed_email')
);

DELETE FROM public.password_reset_token
WHERE user_id IN (
    SELECT id
    FROM public.app_user
    WHERE lower(username) = lower(:'seed_username')
       OR lower(email) = lower(:'seed_email')
);

SELECT username, email, role, auth_provider, is_enabled
FROM public.app_user
WHERE lower(username) = lower(:'seed_username')
   OR lower(email) = lower(:'seed_email')
ORDER BY id;
SQL
echo "Seed admin user is ready."
