services:
  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-sa}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USERNAME:-novaflow}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD:-novaflow}
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 6
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit:v1.30.1
    container_name: mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: unless-stopped

  eureka:
    image: steeltoeoss/eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_REGISTERWITH_EUREKA: "false"
      EUREKA_CLIENT_FETCHREGISTRY: "false"
      EUREKA_SERVER_ENABLESELFPRESERVATION: "false"
      SPRING_APPLICATION_NAME: discovery-server
    restart: unless-stopped

  config-server:
    image: config-server
    container_name: config-server
    depends_on:
      - eureka
    ports:
      - "7090:7090"
    volumes:
      - ../common-config:/config:ro
    environment:
      SPRING_PROFILES_ACTIVE: native
      SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS: file:/config/{application},file:/config
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka
    restart: unless-stopped

volumes:
  postgres_data:
  rabbitmq_data:
