server:
  port: ${SERVER_PORT:7090}

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: git@bitbucket.org:novaflow/common-config.git
          private-key: /root/.ssh/bitbucket_rsa
          clone-on-start: true
          strict-host-key-checking: false
          searchPaths: '{application}'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:8761/eureka
